baseURL = "https://halfgray.xyz/licenses/"
languageCode = "en-US"
title = "Half-Gray Open Licenses"
theme = "hyde-y"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
sidebar = "left"

[outputFormats.PlainText]
mediaType = "text/plain"
baseName = "plain_text"
isPlainText = "true"
