baseURL = "https://halfgray.xyz/licenses/"
languageCode = "en-US"
title = "Half-Gray Open Licenses"
theme = "hyde-y"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
sidebar = "left"

[security.exec]
allow = "^pandoc$"

[outputFormats.PlainText]
mediaType = "text/plain"
baseName = "plain_text"
isPlainText = "true"
